### ISSUE TITLE
Option for different colors for outer and inner

### ISSUE THREAD

**Issue by VirtualL** [Rocka84/dual-gauge-card#3]
Hello , I would love to have an option to make color chose for outer and inner separately 
A good example of the need : SpeedTest result 
My ISP is : 200 Mbps Download and 50 Upload 
so performance detection is easy if the color are "green" if Download is 180+ and Upload is 45+

The config after will be something like this:
```
              - type: custom:dual-gauge-card
                title: SpeetTest
                min: 0
                max: 200
                outer:
                  entity: sensor.speedtest_download
                  label: "Download"
                  unit: "Mbps"
                  colors:
                    - color: 'var(--label-badge-red)'
                      value: 50
                    - color: 'var(--label-badge-yellow)'
                      value: 150
                    - color: 'var(--label-badge-green)'
                      value: 180
                inner:
                  entity: sensor.speedtest_upload
                  label: "Upload"
                  unit: "Mbps"
                  colors:
                    - color: 'var(--label-badge-red)'
                      value: 10
                    - color: 'var(--label-badge-yellow)'
                      value: 40
                    - color: 'var(--label-badge-green)'
                      value: 45
```

Thanks!
